services:

  x11:
    build: ./tools/docker/dockerfiles/x11/
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    restart: always
    links:
      - project
    stdin_open: true
    tty: true
    privileged: true

  chrome:
    build: ./tools/docker/dockerfiles/chrome/
    command: chromium-browser --kiosk https://plentify.io --no-first-run --touch-events=enabled --fast --fast-start --disable-popup-blocking --disable-infobars --disable-session-crashed-bubble --disable-tab-switcher --disable-translate --enable-low-res-tiling
    restart: always
    environment:
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
    links:
      - project
      - x11
    stdin_open: true
    tty: true
    privileged: true
