project: 
  build: ./src
  ports:
    - "80:80"
  expose:
    - 80

x11:
  build: ./tools/docker/dockerfiles/x11/
  environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  command:  x